#include "levels.h"
#include "defines.h"

const uint8_t level1[MAP_FULL_SIZE] = {
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, W_TREE,W_IS,  W_WIN, EMPTY, EMPTY, EMPTY, W_WALL, W_IS, W_STOP, EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  WALL,   WALL,  WALL,  WALL, WALL,  WALL,   WALL,   WALL, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,  GIFT, EMPTY, EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, SANTA, EMPTY, EMPTY, EMPTY,  GIFT, EMPTY, EMPTY, EMPTY,   TREE, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,  GIFT, EMPTY, EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY,  WALL,  WALL,  WALL,  WALL,  WALL, WALL,  WALL,   WALL,   WALL, EMPTY, EMPTY, 
EMPTY, EMPTY, W_SANTA,W_IS, W_YOU, EMPTY, EMPTY, EMPTY, W_GIFT, W_IS, W_PUSH, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, 
};

const uint8_t level2[MAP_FULL_SIZE] = {
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  
WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, EMPTY, EMPTY, W_WIN, EMPTY, WALL,  
WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  
WALL,  EMPTY, W_GIFT,W_IS, W_PUSH, EMPTY, GIFT,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  
WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, SANTA, EMPTY, EMPTY, WALL,  
WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, W_SANTA,W_IS, W_YOU, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_WALL, W_IS, W_STOP,EMPTY, 
};

const uint8_t level3[MAP_FULL_SIZE] = {
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, W_SANTA,EMPTY, EMPTY, EMPTY, EMPTY, W_GIFT,WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, 
EMPTY, W_IS,  EMPTY, EMPTY, EMPTY, EMPTY, W_IS,  WALL,  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
EMPTY, W_YOU, EMPTY, EMPTY, EMPTY, EMPTY, W_WIN, WALL,  EMPTY, GIFT,  EMPTY, WALL,  EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, 
EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
EMPTY, WALL,  EMPTY, W_WALL,W_IS,  W_STOP,EMPTY, EMPTY, SANTA,  EMPTY, EMPTY, WALL,  EMPTY, 
EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, 
};

const uint8_t level4[MAP_FULL_SIZE] = {
W_SANTA,WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  W_SNOW,
W_IS,  WALL,  EMPTY, EMPTY, EMPTY, W_TREE,W_IS,  W_PUSH,EMPTY, EMPTY, EMPTY, WALL,  W_IS,  
W_YOU, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  W_SINK,
EMPTY, WALL,  EMPTY, SANTA,  EMPTY, EMPTY, EMPTY, EMPTY, TREE,  TREE,  EMPTY, WALL,  EMPTY, 
EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
EMPTY, WALL,  WALL,  WALL,  WALL,  SNOW,  SNOW,  SNOW,  WALL,  WALL,  WALL,  WALL,  EMPTY, 
EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
W_WALL,WALL,  SNOW,  SNOW,  SNOW,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
W_IS,  WALL,  SNOW,  SNOW,  SNOW,  EMPTY, EMPTY, W_GIFT,W_IS,  W_WIN, EMPTY, WALL,  EMPTY, 
W_STOP,WALL,  GIFT,  SNOW,  SNOW,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
};

const uint8_t level5[MAP_FULL_SIZE] = {
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
W_SANTA,EMPTY, EMPTY, TREE,  EMPTY, EMPTY, EMPTY, TREE,  EMPTY, EMPTY, EMPTY, EMPTY, W_WALL,
W_IS,  EMPTY, W_TREE,W_IS,  W_PUSH,EMPTY, EMPTY, EMPTY, SNOW,  SNOW,  SNOW,  EMPTY, W_IS,  
W_YOU, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, SNOW,  GIFT,  SNOW,  EMPTY, W_STOP,
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, SNOW,  SNOW,  SNOW,  EMPTY, EMPTY, 
EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, EMPTY, TREE,  EMPTY, EMPTY, EMPTY, 
EMPTY, WALL,  EMPTY, SANTA,  EMPTY, TREE,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_GIFT,
EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_IS,  
EMPTY, EMPTY, EMPTY, EMPTY, TREE,  EMPTY, EMPTY, EMPTY, EMPTY, TREE,  EMPTY, EMPTY, W_WIN, 
EMPTY, W_SNOW,W_IS,  W_STOP,EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
};

const uint8_t level6[MAP_FULL_SIZE] = {
W_LAVA,W_IS,  W_KILL,TREE,  EMPTY, WALL,  LAVA,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, 
W_TREE,W_IS,  W_STOP,TREE,  EMPTY, WALL,  LAVA,  EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
W_GIFT,W_IS,  W_WIN, TREE,  EMPTY, WALL,  LAVA,  EMPTY, EMPTY, GIFT,  EMPTY, WALL,  EMPTY, 
TREE,  TREE,  TREE,  TREE,  EMPTY, WALL,  LAVA,  EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  LAVA,  EMPTY, WALL,  WALL,  WALL,  WALL,  EMPTY, 
EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  
EMPTY, WALL,  SANTA,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, WALL,  WALL,  WALL,  WALL,  W_WALL,W_IS,  W_STOP,WALL,  EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, W_SANTA,W_IS,  W_YOU, WALL,  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, EMPTY, EMPTY, 
};

const uint8_t level7[MAP_FULL_SIZE] = {
EMPTY, EMPTY, EMPTY, EMPTY, W_WALL,W_IS,  W_STOP,EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  W_SANTA,W_IS,  W_YOU, EMPTY, EMPTY, W_WIN, EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, W_GIFT,EMPTY, EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  SANTA,  EMPTY, EMPTY, GIFT,  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
};

const uint8_t level8[MAP_FULL_SIZE] = {
EMPTY, EMPTY, WALL,  SANTA,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  LAVA,  LAVA,  LAVA,  EMPTY, EMPTY, W_WALL,EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_IS,  EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  EMPTY, W_LAVA,W_IS,  W_STOP,EMPTY, W_KILL,EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, W_GIFT,W_IS,  W_WIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, W_WALL,W_IS,  W_STOP,EMPTY, EMPTY, EMPTY, W_SANTA,W_IS,  W_YOU, EMPTY, EMPTY, 
};

const uint8_t level9[MAP_FULL_SIZE] = {
EMPTY, EMPTY, W_WALL,W_IS,  W_STOP,EMPTY, EMPTY, EMPTY, EMPTY, W_SANTA,W_IS,  W_YOU, EMPTY, 
EMPTY, WALL,  WALL,  WALL,  EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, 
EMPTY, WALL,  SANTA,  WALL,  EMPTY, EMPTY, WALL,  W_LOVE,EMPTY, W_WIN, WALL,  EMPTY, EMPTY, 
EMPTY, WALL,  EMPTY, WALL,  EMPTY, EMPTY, WALL,  W_LOVE,W_IS,  W_SWAP,WALL,  EMPTY, EMPTY, 
EMPTY, WALL,  EMPTY, WALL,  EMPTY, EMPTY, WALL,  WALL,  EMPTY, WALL,  WALL,  EMPTY, EMPTY, 
EMPTY, WALL,  LOVE,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, WALL,  WALL,  EMPTY, EMPTY, 
EMPTY, WALL,  EMPTY, TREE,  EMPTY, EMPTY, EMPTY, LOVE,  EMPTY, EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, W_TREE,W_IS,  W_PUSH,EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
};

const uint8_t level10[MAP_FULL_SIZE] = {
EMPTY, EMPTY, TREE,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_GIFT,W_IS,  W_WIN, EMPTY, EMPTY, 
W_WALL,EMPTY, TREE,  W_LAVA,W_IS,  W_STOP,EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  
W_IS,  EMPTY, TREE,  EMPTY, W_LOVE,W_IS,  W_YOU, EMPTY, WALL,  LOVE,  EMPTY, EMPTY, LAVA,  
W_STOP,EMPTY, TREE,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  
EMPTY, EMPTY, TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  
EMPTY, EMPTY, W_SANTA,W_IS,  W_YOU, EMPTY, TREE,  EMPTY, W_TREE,W_IS,  W_STOP,EMPTY, TREE,  
SANTA,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, TREE,  LAVA,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  TREE,  EMPTY, EMPTY, EMPTY, GIFT,  EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  LAVA,  TREE,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
};

const uint8_t level11[MAP_FULL_SIZE] = {
WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  
WALL,  W_LAVA,W_LAVA,W_LAVA,WALL,  SANTA,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, SNOW,  SNOW,  
WALL,  W_IS,  W_IS,  W_IS,  WALL,  EMPTY, WALL,  W_EMPTY,EMPTY, TREE,  TREE,  SNOW,  WALL,  
WALL,  EMPTY, W_STOP,W_KILL,EMPTY, EMPTY, EMPTY, W_PUSH,EMPTY, LAVA,  LAVA,  SNOW,  WALL,  
WALL,  EMPTY, WALL,  WALL,  WALL,  EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  SNOW,  SNOW,  WALL,  
WALL,  EMPTY, WALL,  W_TREE,W_IS,  EMPTY, SNOW,  SNOW,  SNOW,  SNOW,  SNOW,  SNOW,  WALL,  
WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  SNOW,  WALL,  WALL,  WALL,  EMPTY, WALL,  WALL,  
WALL,  W_WALL,W_IS,  W_STOP,WALL,  W_SANTA,SNOW,  EMPTY, GIFT,  EMPTY, EMPTY, EMPTY, WALL,  
WALL,  W_GIFT,W_IS,  W_WIN, WALL,  W_IS,  SNOW,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  
WALL,  W_SNOW,W_IS,  W_SINK,WALL,  W_YOU, SNOW,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  
};

const uint8_t level12[MAP_FULL_SIZE] = {
GIFT,  EMPTY, EMPTY, W_GIFT,W_SANTA,W_WALL,EMPTY, EMPTY, EMPTY, EMPTY, W_TREE,W_IS,  W_STOP,
TREE,  TREE,  EMPTY, W_IS,  W_IS,  W_IS,  LAVA,  LAVA,  SANTA,  EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  W_WIN, W_YOU, W_STOP,WALL,  TREE,  TREE,  TREE,  TREE,  TREE,  EMPTY, 
W_LAVA,EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, W_LOVE,EMPTY, TREE,  EMPTY, 
EMPTY, EMPTY, WALL,  W_WALL,W_IS,  W_STOP,WALL,  GIFT,  EMPTY, EMPTY, EMPTY, TREE,  EMPTY, 
EMPTY, EMPTY, W_PUSH,EMPTY, W_IS,  TREE,  TREE,  EMPTY, EMPTY, EMPTY, EMPTY, TREE,  EMPTY, 
EMPTY, EMPTY, TREE,  EMPTY, EMPTY, EMPTY, TREE,  W_LAVA,W_IS,  W_KILL,EMPTY, TREE,  EMPTY, 
EMPTY, EMPTY, TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, W_IS,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, W_LOVE,EMPTY, EMPTY, EMPTY, EMPTY, W_LOVE,W_IS,  W_PUSH,EMPTY, EMPTY, W_LAVA,
};

const uint8_t level13[] = {
W_TREE,W_IS,  W_PUSH,EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_PUSH,W_LAVA,W_IS,  W_SINK,
LAVA,  LAVA,  EMPTY, EMPTY, W_LOVE,W_IS,  W_KILL,LOVE,  EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  
LAVA,  LAVA,  LAVA,  LAVA,  EMPTY, SANTA,  EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  LAVA,  LAVA,  
W_LAVA,LAVA,  LAVA,  LAVA,  LOVE,  LOVE,  LOVE,  LOVE,  LOVE,  LAVA,  LAVA,  LAVA,  W_SANTA,
W_IS,  EMPTY, LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  EMPTY, EMPTY, W_IS,  
W_KILL,EMPTY, LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  EMPTY, W_YOU, 
LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  
LAVA,  GIFT,  LAVA,  LAVA,  EMPTY, LAVA,  LOVE,  LAVA,  EMPTY, LAVA,  LAVA,  EMPTY, W_GIFT,
LAVA,  LAVA,  LAVA,  LOVE,  LOVE,  LAVA,  LAVA,  LOVE,  LOVE,  LOVE,  LAVA,  LAVA,  W_IS,  
LAVA,  LAVA,  LAVA,  LOVE,  LAVA,  LOVE,  LAVA,  EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  W_WIN, 
};

const uint8_t level14[] = {
EMPTY, EMPTY, WALL,  EMPTY, W_SANTA,EMPTY, LAVA,  EMPTY, W_LOVE,EMPTY, WALL,  EMPTY, EMPTY, 
SANTA,  EMPTY, WALL,  EMPTY, W_IS,  EMPTY, LAVA,  EMPTY, W_IS,  EMPTY, WALL,  EMPTY, LOVE,  
EMPTY, EMPTY, WALL,  EMPTY, W_YOU, EMPTY, LAVA,  EMPTY, W_YOU, EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, WALL,  WALL,  EMPTY, EMPTY, EMPTY, LAVA,  EMPTY, EMPTY, EMPTY, WALL,  WALL,  EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, W_TREE,EMPTY, EMPTY, EMPTY, LAVA,  EMPTY, EMPTY, EMPTY, W_WIN, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
W_WALL,W_IS,  W_STOP,EMPTY, EMPTY, EMPTY, LAVA,  EMPTY, EMPTY, EMPTY, W_LAVA,W_IS,  W_SINK,
};

const uint8_t level15[] = {
SANTA,  EMPTY, EMPTY, EMPTY, EMPTY, SNOW,  SNOW,  SNOW,  EMPTY, WALL,  EMPTY, EMPTY, W_LAVA,
EMPTY, EMPTY, EMPTY, EMPTY, WALL,  SNOW,  SNOW,  W_IS,  EMPTY, EMPTY, EMPTY, EMPTY, W_IS,
LAVA,  LAVA,  LAVA,  WALL,  WALL,  EMPTY, W_SNOW,EMPTY, W_IS,  WALL,  EMPTY, EMPTY, W_KILL,
W_SANTA,W_IS,  W_YOU, WALL,  WALL,  EMPTY, TREE,  EMPTY, EMPTY, WALL,  W_TREE,EMPTY, EMPTY,
W_SNOW,W_IS,  W_SINK,WALL,  WALL,  EMPTY, SANTA,  W_PUSH,EMPTY, WALL,  EMPTY, EMPTY, EMPTY,
W_WALL,W_IS,  W_STOP,WALL,  WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
LAVA,  LAVA,  WALL,  EMPTY, SNOW,  SNOW,  SNOW,  SNOW,  SNOW,  SNOW,  SNOW,  SNOW,  SNOW,
EMPTY, EMPTY, EMPTY, EMPTY, WALL,  SNOW,  SNOW,  SNOW,  SNOW,  SNOW,  SNOW,  SNOW,  SNOW,
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, SNOW,  SNOW,  SNOW,  EMPTY, GIFT,  EMPTY, EMPTY, EMPTY,
SANTA,  EMPTY, EMPTY, EMPTY, SNOW,  SNOW,  W_GIFT,EMPTY, EMPTY, W_IS,  W_WIN, EMPTY, WALL,
};

const uint8_t level16[] = {
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  LAVA,  W_GIFT,
EMPTY, W_SANTA,W_IS,  W_YOU, SANTA,  WALL,  EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  LAVA,  W_IS,
EMPTY, EMPTY, EMPTY, EMPTY, WALL,  WALL,  EMPTY, EMPTY, LAVA,  LAVA,  LAVA,  EMPTY, W_WIN,
WALL,  WALL,  WALL,  EMPTY, EMPTY, TREE,  EMPTY, EMPTY, LAVA,  LAVA,  LAVA,  EMPTY, EMPTY,
WALL,  W_TREE,WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, LAVA,  LAVA,  LAVA,  EMPTY, EMPTY,
EMPTY, W_IS,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  LAVA,  EMPTY, EMPTY,
EMPTY, W_PUSH,EMPTY, EMPTY, W_LAVA,EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  EMPTY, EMPTY, EMPTY,
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  LAVA,  GIFT,  EMPTY, EMPTY,
WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, LAVA,  LAVA,  LAVA,  LAVA,  EMPTY, EMPTY, EMPTY,
WALL,  W_LAVA,W_IS,  W_KILL,WALL,  EMPTY, LAVA,  LAVA,  LAVA,  EMPTY, W_WALL,W_IS,  W_STOP,
};

const uint8_t level17[] = {
WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,
WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, WALL,
WALL,  EMPTY, EMPTY, W_SANTA,W_IS,  W_YOU, EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,
WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, WALL,  W_WALL,
WALL,  EMPTY, SANTA,  EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, GIFT,  WALL,  W_IS,
WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, WALL,  W_STOP,
WALL,  EMPTY, EMPTY, W_GIFT,W_IS,  W_WIN, EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,
WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, WALL,
WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
};

const uint8_t level18[] = {
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
EMPTY, W_GIFT,W_IS,  W_WIN, EMPTY, WALL,  SANTA,  EMPTY, LAVA,  EMPTY, EMPTY, W_WALL,EMPTY,
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  LAVA,  LAVA,  LAVA,  EMPTY, EMPTY, W_IS,  EMPTY,
EMPTY, W_SANTA,W_IS,  W_YOU, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_STOP,EMPTY,
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, W_LAVA,W_IS,  W_KILL,EMPTY, EMPTY, EMPTY,
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
W_WALL,W_IS,  W_KILL,EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,
};

const uint8_t level19[] = {
LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  EMPTY, LAVA,  LAVA,  LAVA,  LAVA,  W_LAVA,
LAVA,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  EMPTY, EMPTY, LAVA,  W_IS,
LAVA,  EMPTY, W_SNOW,EMPTY, EMPTY, EMPTY, W_SANTA,WALL,  WALL,  EMPTY, EMPTY, LAVA,  W_KILL,
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_IS,  WALL,  EMPTY, EMPTY, LAVA,  LAVA,  LAVA,
EMPTY, EMPTY, EMPTY, EMPTY, SANTA,  EMPTY, W_YOU, WALL,  EMPTY, TREE,  LAVA,  SNOW,  EMPTY,
LAVA,  EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  W_GIFT,EMPTY, LAVA,  EMPTY, GIFT,
LAVA,  EMPTY, W_WALL,W_IS,  W_STOP,EMPTY, LAVA,  LAVA,  EMPTY, EMPTY, EMPTY, LAVA,  LAVA,
LAVA,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  EMPTY, W_IS,  EMPTY, W_TREE,LAVA,
LAVA,  EMPTY, LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  WALL,  W_WIN, EMPTY, EMPTY, W_IS,  LAVA,
LAVA,  EMPTY, LAVA,  LAVA,  EMPTY, EMPTY, LAVA,  LAVA,  LAVA,  EMPTY, EMPTY, W_YOU, LAVA,
};

const uint8_t level20[] = {
GIFT,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,
EMPTY, WALL,  EMPTY, EMPTY, EMPTY, TREE,  WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
EMPTY, WALL,  EMPTY, W_LAVA,EMPTY, EMPTY, WALL,  EMPTY, W_IS,  EMPTY, EMPTY, EMPTY, EMPTY,
EMPTY, EMPTY, WALL,  WALL,  WALL,  EMPTY, WALL,  EMPTY, EMPTY, LAVA,  LAVA,  LAVA,  W_SNOW,
EMPTY, EMPTY, W_IS,  EMPTY, WALL,  EMPTY, WALL,  EMPTY, W_TREE,LAVA,  W_LAVA,LAVA,  LAVA,
EMPTY, EMPTY, W_SNOW,EMPTY, WALL,  EMPTY, WALL,  EMPTY, EMPTY, LAVA,  W_IS,  LAVA,  W_SNOW,
W_WIN, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, WALL,  EMPTY, EMPTY, LAVA,  W_KILL,LAVA,  W_IS,
EMPTY, EMPTY, WALL,  WALL,  EMPTY, EMPTY, EMPTY, WALL,  SNOW,  LAVA,  LAVA,  LAVA,  EMPTY,
EMPTY, EMPTY, EMPTY, W_GIFT,EMPTY, EMPTY, EMPTY, WALL,  WALL,  WALL,  W_SANTA,W_IS,  W_YOU,
EMPTY, W_IS,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  W_WALL,W_IS,  W_STOP,WALL,  SANTA,
};

const uint8_t level21[] = {
W_SNOW,W_IS,  W_SINK,WALL,  WALL,  WALL,  GIFT,  WALL,  WALL,  WALL,  W_SANTA,W_IS,  W_YOU,
W_WALL,W_IS,  W_STOP,WALL,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  WALL,  W_GIFT,W_IS,  W_WIN,
WALL,  WALL,  WALL,  WALL,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  WALL,  WALL,  WALL,  WALL,
LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,
EMPTY, LOVE,  EMPTY, W_GIFT,LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  EMPTY, EMPTY, EMPTY, LOVE,
EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  EMPTY, SNOW,  EMPTY, EMPTY,
EMPTY, W_SNOW,SANTA,  TREE,  EMPTY, LAVA,  W_IS,  LAVA,  EMPTY, W_TREE,EMPTY, EMPTY, EMPTY,
EMPTY, EMPTY, SNOW,  EMPTY, EMPTY, EMPTY, LAVA,  EMPTY, EMPTY, LOVE,  EMPTY, TREE,  EMPTY,
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, SNOW,  SNOW,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
W_TREE,W_IS,  W_PUSH,EMPTY, EMPTY, TREE,  EMPTY, EMPTY, EMPTY, EMPTY, W_LAVA,W_IS,  W_SINK,
};

const uint8_t level22[] = {
};

const uint8_t level23[] = {
};

const uint8_t level24[] = {
};

const uint8_t level25[] = {
};

const uint8_t * levels[] = {
  level1, level2, level3, level4, level5, level6, level7, level8,
  level9, level10, level11, level12, level13, level14, level15,
  level16, level17, level18, level19, level20, level21, level22,
  level23, level24, level25
};
